
SwatterData = {
	["enabled"] = true,
	["warning"] = true,
	["combat"] = false,
	["errors"] = {
		{
			["message"] = "Error: AddOn TradeSkillMaster attempted to call a forbidden function (CastSpell()) from a tainted execution path.",
			["count"] = 1,
			["addons"] = "  Swatter, v8.2.6377 (SwimmingSeadragon)\n  AtlasLootClassic, vv1.1.8-beta\n  AtlasLootClassicDungeonsAndRaids, vv1.1.8-beta\n  AttackTimer, v\n  AucAdvanced, v8.2.6385 (SwimmingSeadragon)\n  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)\n  AucScanData, v8.2.6365 (SwimmingSeadragon)\n  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)\n  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)\n  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)\n  AucStatSimple, v8.2.6368 (SwimmingSeadragon)\n  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)\n  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)\n  AutoEquip, v\n  BagnonForever, v1.1.1\n  Bartender4, v4.8.5\n  BeanCounter, v8.2.6381 (SwimmingSeadragon)\n  BFGadgets, v\n  BFQuest, v\n  BFTooltip, v\n  BigFoot, v\n  BigFootChat, v\n  BlizzMove, vv1.2.2\n  BuffMaster, v\n  ChannelFilter, v\n  ClassicCodex, v1.2.1\n  ClassicThreatMeter, v1.06\n  Combuctor, v603\n  DBMCore, v1.13.5\n  DBMDefaultSkin, v\n  DBMStatusBarTimers, v\n  Enchantrix, v8.2.6392 (SwimmingSeadragon)\n  EventAlertMod, v8.0.1\n  HandyNotes, vr317\n  HandyNotesDungeonLocationsClassic, v1.01\n  HandyNotesFlightMastersClassic, v1.04\n  HandyNotesTravelGuideClassic, vv2.1.0\n  Informant, v8.2.6374 (SwimmingSeadragon)\n  ItemInfo, v\n  MailMod, v\n  Mapster, v1.8.4\n  Masque, vClassic-8.2.5-Beta-2\n  MerInspect, v2.2.0\n  MonkeyBuddy, v\n  MonkeyLibrary, v\n  MonkeyQuest, v\n  MonkeyQuestLog, v\n  MySlot, vclassic-5.2.6-alpha\n  NeatPlates, v1.13.2.12-Classic\n  NeatPlatesAlvara, v5a\n  NeatPlatesBlizzardPlates, v1.5\n  NeatPlatesClassicPlates, v\n  NeatPlatesGraphite, v\n  NeatPlatesGrey, v\n  NeatPlatesNeon, v\n  NeatPlatesQuatre, v\n  NeatPlatesRenaitre, vv7.0.3\n  NeatPlatesRoth, v\n  NeatPlatesSimple, v7.3.0\n  NeatPlatesSlimHorizontal, v2.2\n  NeatPlatesSlimVertical, v2.2\n  NeatPlatesHub, v\n  NeatPlatesWidgets, v\n  PlayerLink, v\n  QuestFrameFixer, v1.1.1\n  QuestLogEx, v1.2\n  QuickCompare, v\n  RaidAlerter, v5.3.1\n  RealMobHealth, v2.3\n  Recount, vv1.13.2b\n  RepairHelper, v\n  Scrap, v13.19\n  ScrapMerchant, v13.19\n  ScrapSpotlight, v13.19\n  SellerHelper, v\n  ShadowedUnitFrames, vv4.2-Classic-Beta6\n  SlideBar, v8.2.6375 (SwimmingSeadragon)\n  Stubby, v8.2.6376 (SwimmingSeadragon)\n  TheBurningTrade, v\n  TrackResources, v0.7\n  TradeSkillMaster, vv4.8.6\n  WhatsTraining, v1.7\n  WhisperPop, v3.1\n  BlizRuntimeLib_zhCN v1.13.2.11302 <none>\n  (ck=8fc)\n",
			["timestamp"] = "2019-09-07 00:53:15",
			["context"] = "AddOn: TradeSkillMaster",
			["stack"] = "[C]: in function `CastSpell'\nInterface\\FrameXML\\SpellBookFrame.lua:351: in function `SpellButton_OnClick'\n[string \"*:OnClick\"]:4: in function <[string \"*:OnClick\"]:1>\n",
		}, -- [1]
		{
			["message"] = "Error: AddOn TradeSkillMaster attempted to call a forbidden function (CastSpell()) from a tainted execution path.",
			["count"] = 1,
			["addons"] = "  Swatter, v8.2.6377 (SwimmingSeadragon)\n  AtlasLootClassic, vv1.1.8-beta\n  AttackTimer, v\n  AucAdvanced, v8.2.6385 (SwimmingSeadragon)\n  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)\n  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)\n  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)\n  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)\n  AucStatSimple, v8.2.6368 (SwimmingSeadragon)\n  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)\n  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)\n  AutoEquip, v\n  BagnonForever, v1.1.1\n  Bartender4, v4.8.5\n  BeanCounter, v8.2.6381 (SwimmingSeadragon)\n  BFGadgets, v\n  BFQuest, v\n  BFTooltip, v\n  BigFoot, v\n  BigFootChat, v\n  BlizzMove, vv1.2.2\n  BuffMaster, v\n  ChannelFilter, v\n  ClassicCodex, v1.2.1\n  ClassicThreatMeter, v1.06\n  Combuctor, v603\n  DBMCore, v1.13.5\n  DBMDefaultSkin, v\n  DBMStatusBarTimers, v\n  Enchantrix, v8.2.6392 (SwimmingSeadragon)\n  EventAlertMod, v8.0.1\n  HandyNotes, vr317\n  HandyNotesDungeonLocationsClassic, v1.01\n  HandyNotesFlightMastersClassic, v1.04\n  HandyNotesTravelGuideClassic, vv2.1.0\n  Informant, v8.2.6374 (SwimmingSeadragon)\n  ItemInfo, v\n  MailMod, v\n  Mapster, v1.8.4\n  Masque, vClassic-8.2.5-Beta-2\n  MerInspect, v2.2.0\n  MonkeyBuddy, v\n  MonkeyLibrary, v\n  MonkeyQuest, v\n  MonkeyQuestLog, v\n  MySlot, vclassic-5.2.6-alpha\n  NeatPlates, v1.13.2.12-Classic\n  NeatPlatesAlvara, v5a\n  NeatPlatesBlizzardPlates, v1.5\n  NeatPlatesClassicPlates, v\n  NeatPlatesGraphite, v\n  NeatPlatesGrey, v\n  NeatPlatesNeon, v\n  NeatPlatesQuatre, v\n  NeatPlatesRenaitre, vv7.0.3\n  NeatPlatesRoth, v\n  NeatPlatesSimple, v7.3.0\n  NeatPlatesSlimHorizontal, v2.2\n  NeatPlatesSlimVertical, v2.2\n  NeatPlatesHub, v\n  NeatPlatesWidgets, v\n  PlayerLink, v\n  QuestFrameFixer, v1.1.1\n  QuestLogEx, v1.2\n  QuickCompare, v\n  RaidAlerter, v5.3.1\n  RealMobHealth, v2.3\n  Recount, vv1.13.2b\n  RepairHelper, v\n  Scrap, v13.19\n  ScrapSpotlight, v13.19\n  SellerHelper, v\n  ShadowedUnitFrames, vv4.2-Classic-Beta6\n  SlideBar, v8.2.6375 (SwimmingSeadragon)\n  Stubby, v8.2.6376 (SwimmingSeadragon)\n  TheBurningTrade, v\n  TrackResources, v0.7\n  TradeSkillMaster, vv4.8.6\n  WhatsTraining, v1.7\n  WhisperPop, v3.1\n  BlizRuntimeLib_zhCN v1.13.2.11302 <none>\n  (ck=886)\n",
			["timestamp"] = "2019-09-07 00:53:37",
			["context"] = "AddOn: TradeSkillMaster",
			["stack"] = "[C]: in function `CastSpell'\nInterface\\FrameXML\\SpellBookFrame.lua:351: in function `SpellButton_OnClick'\n[string \"*:OnClick\"]:4: in function <[string \"*:OnClick\"]:1>\n",
		}, -- [2]
		{
			["message"] = "Note: AddOn BigFoot attempted to call a protected function (CompactPartyFrame:unusedFunc()) during combat lockdown.",
			["count"] = 4,
			["addons"] = "  Swatter, v8.2.6377 (SwimmingSeadragon)\n  AtlasLootClassic, vv1.1.8-beta\n  AttackTimer, v\n  AucAdvanced, v8.2.6385 (SwimmingSeadragon)\n  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)\n  AucScanData, v8.2.6365 (SwimmingSeadragon)\n  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)\n  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)\n  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)\n  AucStatSimple, v8.2.6368 (SwimmingSeadragon)\n  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)\n  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)\n  AutoEquip, v\n  BagnonForever, v1.1.1\n  Bartender4, v4.8.5\n  BeanCounter, v8.2.6381 (SwimmingSeadragon)\n  BFGadgets, v\n  BFQuest, v\n  BFTooltip, v\n  BigFoot, v\n  BigFootChat, v\n  BlizzMove, vv1.2.2\n  BuffMaster, v\n  ChannelFilter, v\n  ClassicCodex, v1.2.1\n  ClassicThreatMeter, v1.06\n  Combuctor, v603\n  DBMCore, v1.13.5\n  DBMDefaultSkin, v\n  DBMStatusBarTimers, v\n  Enchantrix, v8.2.6392 (SwimmingSeadragon)\n  EventAlertMod, v8.0.1\n  HandyNotes, vr317\n  HandyNotesDungeonLocationsClassic, v1.01\n  HandyNotesFlightMastersClassic, v1.04\n  HandyNotesTravelGuideClassic, vv2.1.0\n  Informant, v8.2.6374 (SwimmingSeadragon)\n  ItemInfo, v\n  MailMod, v\n  Mapster, v1.8.4\n  Masque, vClassic-8.2.5-Beta-2\n  MerInspect, v2.2.0\n  MonkeyBuddy, v\n  MonkeyLibrary, v\n  MonkeyQuest, v\n  MonkeyQuestLog, v\n  MySlot, vclassic-5.2.6-alpha\n  NeatPlates, v1.13.2.12-Classic\n  NeatPlatesAlvara, v5a\n  NeatPlatesBlizzardPlates, v1.5\n  NeatPlatesClassicPlates, v\n  NeatPlatesGraphite, v\n  NeatPlatesGrey, v\n  NeatPlatesNeon, v\n  NeatPlatesQuatre, v\n  NeatPlatesRenaitre, vv7.0.3\n  NeatPlatesRoth, v\n  NeatPlatesSimple, v7.3.0\n  NeatPlatesSlimHorizontal, v2.2\n  NeatPlatesSlimVertical, v2.2\n  NeatPlatesHub, v\n  NeatPlatesWidgets, v\n  PlayerLink, v\n  QuestFrameFixer, v1.1.1\n  QuestLogEx, v1.2\n  QuickCompare, v\n  RaidAlerter, v5.3.1\n  RealMobHealth, v2.3\n  Recount, vv1.13.2b\n  RepairHelper, v\n  Scrap, v13.19\n  ScrapOptions, v13.19\n  ScrapSpotlight, v13.19\n  SellerHelper, v\n  ShadowedUnitFrames, vv4.2-Classic-Beta6\n  SlideBar, v8.2.6375 (SwimmingSeadragon)\n  Stubby, v8.2.6376 (SwimmingSeadragon)\n  TheBurningTrade, v\n  TrackResources, v0.7\n  TradeSkillMaster, vv4.8.6\n  WhatsTraining, v1.7\n  WhisperPop, v3.1\n  BlizRuntimeLib_zhCN v1.13.2.11302 <none>\n  (ck=8ca)\n",
			["timestamp"] = "2019-09-07 11:20:38",
			["context"] = "AddOn: BigFoot",
			["stack"] = "[C]: in function `unusedFunc'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:160: in function `CompactRaidFrameContainer_LayoutFrames'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:130: in function `CompactRaidFrameContainer_TryUpdate'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:57: in function `CompactRaidFrameContainer_OnEvent'\n[string \"*:OnEvent\"]:1: in function <[string \"*:OnEvent\"]:1>\n",
		}, -- [3]
		{
			["message"] = "Note: AddOn BigFoot attempted to call a protected function (CompactPartyFrame:SetParent()) during combat lockdown.",
			["count"] = 4,
			["addons"] = "  Swatter, v8.2.6377 (SwimmingSeadragon)\n  AtlasLootClassic, vv1.1.8-beta\n  AttackTimer, v\n  AucAdvanced, v8.2.6385 (SwimmingSeadragon)\n  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)\n  AucScanData, v8.2.6365 (SwimmingSeadragon)\n  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)\n  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)\n  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)\n  AucStatSimple, v8.2.6368 (SwimmingSeadragon)\n  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)\n  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)\n  AutoEquip, v\n  BagnonForever, v1.1.1\n  Bartender4, v4.8.5\n  BeanCounter, v8.2.6381 (SwimmingSeadragon)\n  BFGadgets, v\n  BFQuest, v\n  BFTooltip, v\n  BigFoot, v\n  BigFootChat, v\n  BlizzMove, vv1.2.2\n  BuffMaster, v\n  ChannelFilter, v\n  ClassicCodex, v1.2.1\n  ClassicThreatMeter, v1.06\n  Combuctor, v603\n  DBMCore, v1.13.5\n  DBMDefaultSkin, v\n  DBMStatusBarTimers, v\n  Enchantrix, v8.2.6392 (SwimmingSeadragon)\n  EventAlertMod, v8.0.1\n  HandyNotes, vr317\n  HandyNotesDungeonLocationsClassic, v1.01\n  HandyNotesFlightMastersClassic, v1.04\n  HandyNotesTravelGuideClassic, vv2.1.0\n  Informant, v8.2.6374 (SwimmingSeadragon)\n  ItemInfo, v\n  MailMod, v\n  Mapster, v1.8.4\n  Masque, vClassic-8.2.5-Beta-2\n  MerInspect, v2.2.0\n  MonkeyBuddy, v\n  MonkeyLibrary, v\n  MonkeyQuest, v\n  MonkeyQuestLog, v\n  MySlot, vclassic-5.2.6-alpha\n  NeatPlates, v1.13.2.12-Classic\n  NeatPlatesAlvara, v5a\n  NeatPlatesBlizzardPlates, v1.5\n  NeatPlatesClassicPlates, v\n  NeatPlatesGraphite, v\n  NeatPlatesGrey, v\n  NeatPlatesNeon, v\n  NeatPlatesQuatre, v\n  NeatPlatesRenaitre, vv7.0.3\n  NeatPlatesRoth, v\n  NeatPlatesSimple, v7.3.0\n  NeatPlatesSlimHorizontal, v2.2\n  NeatPlatesSlimVertical, v2.2\n  NeatPlatesHub, v\n  NeatPlatesWidgets, v\n  PlayerLink, v\n  QuestFrameFixer, v1.1.1\n  QuestLogEx, v1.2\n  QuickCompare, v\n  RaidAlerter, v5.3.1\n  RealMobHealth, v2.3\n  Recount, vv1.13.2b\n  RepairHelper, v\n  Scrap, v13.19\n  ScrapOptions, v13.19\n  ScrapSpotlight, v13.19\n  SellerHelper, v\n  ShadowedUnitFrames, vv4.2-Classic-Beta6\n  SlideBar, v8.2.6375 (SwimmingSeadragon)\n  Stubby, v8.2.6376 (SwimmingSeadragon)\n  TheBurningTrade, v\n  TrackResources, v0.7\n  TradeSkillMaster, vv4.8.6\n  WhatsTraining, v1.7\n  WhisperPop, v3.1\n  BlizRuntimeLib_zhCN v1.13.2.11302 <none>\n  (ck=8ca)\n",
			["timestamp"] = "2019-09-07 11:20:38",
			["context"] = "AddOn: BigFoot",
			["stack"] = "[C]: in function `SetParent'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:233: in function `CompactRaidFrameContainer_AddGroup'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:215: in function `CompactRaidFrameContainer_AddGroups'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:174: in function `CompactRaidFrameContainer_LayoutFrames'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:130: in function `CompactRaidFrameContainer_TryUpdate'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:57: in function `CompactRaidFrameContainer_OnEvent'\n[string \"*:OnEvent\"]:1: in function <[string \"*:OnEvent\"]:1>\n",
		}, -- [4]
		{
			["message"] = "Note: AddOn BigFoot attempted to call a protected function (CompactPartyFrame:SetFrameStrata()) during combat lockdown.",
			["count"] = 4,
			["addons"] = "  Swatter, v8.2.6377 (SwimmingSeadragon)\n  AtlasLootClassic, vv1.1.8-beta\n  AttackTimer, v\n  AucAdvanced, v8.2.6385 (SwimmingSeadragon)\n  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)\n  AucScanData, v8.2.6365 (SwimmingSeadragon)\n  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)\n  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)\n  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)\n  AucStatSimple, v8.2.6368 (SwimmingSeadragon)\n  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)\n  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)\n  AutoEquip, v\n  BagnonForever, v1.1.1\n  Bartender4, v4.8.5\n  BeanCounter, v8.2.6381 (SwimmingSeadragon)\n  BFGadgets, v\n  BFQuest, v\n  BFTooltip, v\n  BigFoot, v\n  BigFootChat, v\n  BlizzMove, vv1.2.2\n  BuffMaster, v\n  ChannelFilter, v\n  ClassicCodex, v1.2.1\n  ClassicThreatMeter, v1.06\n  Combuctor, v603\n  DBMCore, v1.13.5\n  DBMDefaultSkin, v\n  DBMStatusBarTimers, v\n  Enchantrix, v8.2.6392 (SwimmingSeadragon)\n  EventAlertMod, v8.0.1\n  HandyNotes, vr317\n  HandyNotesDungeonLocationsClassic, v1.01\n  HandyNotesFlightMastersClassic, v1.04\n  HandyNotesTravelGuideClassic, vv2.1.0\n  Informant, v8.2.6374 (SwimmingSeadragon)\n  ItemInfo, v\n  MailMod, v\n  Mapster, v1.8.4\n  Masque, vClassic-8.2.5-Beta-2\n  MerInspect, v2.2.0\n  MonkeyBuddy, v\n  MonkeyLibrary, v\n  MonkeyQuest, v\n  MonkeyQuestLog, v\n  MySlot, vclassic-5.2.6-alpha\n  NeatPlates, v1.13.2.12-Classic\n  NeatPlatesAlvara, v5a\n  NeatPlatesBlizzardPlates, v1.5\n  NeatPlatesClassicPlates, v\n  NeatPlatesGraphite, v\n  NeatPlatesGrey, v\n  NeatPlatesNeon, v\n  NeatPlatesQuatre, v\n  NeatPlatesRenaitre, vv7.0.3\n  NeatPlatesRoth, v\n  NeatPlatesSimple, v7.3.0\n  NeatPlatesSlimHorizontal, v2.2\n  NeatPlatesSlimVertical, v2.2\n  NeatPlatesHub, v\n  NeatPlatesWidgets, v\n  PlayerLink, v\n  QuestFrameFixer, v1.1.1\n  QuestLogEx, v1.2\n  QuickCompare, v\n  RaidAlerter, v5.3.1\n  RealMobHealth, v2.3\n  Recount, vv1.13.2b\n  RepairHelper, v\n  Scrap, v13.19\n  ScrapOptions, v13.19\n  ScrapSpotlight, v13.19\n  SellerHelper, v\n  ShadowedUnitFrames, vv4.2-Classic-Beta6\n  SlideBar, v8.2.6375 (SwimmingSeadragon)\n  Stubby, v8.2.6376 (SwimmingSeadragon)\n  TheBurningTrade, v\n  TrackResources, v0.7\n  TradeSkillMaster, vv4.8.6\n  WhatsTraining, v1.7\n  WhisperPop, v3.1\n  BlizRuntimeLib_zhCN v1.13.2.11302 <none>\n  (ck=8ca)\n",
			["timestamp"] = "2019-09-07 11:20:38",
			["context"] = "AddOn: BigFoot",
			["stack"] = "[C]: in function `SetFrameStrata'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:234: in function `CompactRaidFrameContainer_AddGroup'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:215: in function `CompactRaidFrameContainer_AddGroups'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:174: in function `CompactRaidFrameContainer_LayoutFrames'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:130: in function `CompactRaidFrameContainer_TryUpdate'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:57: in function `CompactRaidFrameContainer_OnEvent'\n[string \"*:OnEvent\"]:1: in function <[string \"*:OnEvent\"]:1>\n",
		}, -- [5]
		{
			["message"] = "Note: AddOn BigFoot attempted to call a protected function (CompactPartyFrame:Show()) during combat lockdown.",
			["count"] = 4,
			["addons"] = "  Swatter, v8.2.6377 (SwimmingSeadragon)\n  AtlasLootClassic, vv1.1.8-beta\n  AttackTimer, v\n  AucAdvanced, v8.2.6385 (SwimmingSeadragon)\n  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)\n  AucScanData, v8.2.6365 (SwimmingSeadragon)\n  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)\n  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)\n  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)\n  AucStatSimple, v8.2.6368 (SwimmingSeadragon)\n  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)\n  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)\n  AutoEquip, v\n  BagnonForever, v1.1.1\n  Bartender4, v4.8.5\n  BeanCounter, v8.2.6381 (SwimmingSeadragon)\n  BFGadgets, v\n  BFQuest, v\n  BFTooltip, v\n  BigFoot, v\n  BigFootChat, v\n  BlizzMove, vv1.2.2\n  BuffMaster, v\n  ChannelFilter, v\n  ClassicCodex, v1.2.1\n  ClassicThreatMeter, v1.06\n  Combuctor, v603\n  DBMCore, v1.13.5\n  DBMDefaultSkin, v\n  DBMStatusBarTimers, v\n  Enchantrix, v8.2.6392 (SwimmingSeadragon)\n  EventAlertMod, v8.0.1\n  HandyNotes, vr317\n  HandyNotesDungeonLocationsClassic, v1.01\n  HandyNotesFlightMastersClassic, v1.04\n  HandyNotesTravelGuideClassic, vv2.1.0\n  Informant, v8.2.6374 (SwimmingSeadragon)\n  ItemInfo, v\n  MailMod, v\n  Mapster, v1.8.4\n  Masque, vClassic-8.2.5-Beta-2\n  MerInspect, v2.2.0\n  MonkeyBuddy, v\n  MonkeyLibrary, v\n  MonkeyQuest, v\n  MonkeyQuestLog, v\n  MySlot, vclassic-5.2.6-alpha\n  NeatPlates, v1.13.2.12-Classic\n  NeatPlatesAlvara, v5a\n  NeatPlatesBlizzardPlates, v1.5\n  NeatPlatesClassicPlates, v\n  NeatPlatesGraphite, v\n  NeatPlatesGrey, v\n  NeatPlatesNeon, v\n  NeatPlatesQuatre, v\n  NeatPlatesRenaitre, vv7.0.3\n  NeatPlatesRoth, v\n  NeatPlatesSimple, v7.3.0\n  NeatPlatesSlimHorizontal, v2.2\n  NeatPlatesSlimVertical, v2.2\n  NeatPlatesHub, v\n  NeatPlatesWidgets, v\n  PlayerLink, v\n  QuestFrameFixer, v1.1.1\n  QuestLogEx, v1.2\n  QuickCompare, v\n  RaidAlerter, v5.3.1\n  RealMobHealth, v2.3\n  Recount, vv1.13.2b\n  RepairHelper, v\n  Scrap, v13.19\n  ScrapOptions, v13.19\n  ScrapSpotlight, v13.19\n  SellerHelper, v\n  ShadowedUnitFrames, vv4.2-Classic-Beta6\n  SlideBar, v8.2.6375 (SwimmingSeadragon)\n  Stubby, v8.2.6376 (SwimmingSeadragon)\n  TheBurningTrade, v\n  TrackResources, v0.7\n  TradeSkillMaster, vv4.8.6\n  WhatsTraining, v1.7\n  WhisperPop, v3.1\n  BlizRuntimeLib_zhCN v1.13.2.11302 <none>\n  (ck=8ca)\n",
			["timestamp"] = "2019-09-07 11:20:38",
			["context"] = "AddOn: BigFoot",
			["stack"] = "[C]: in function `Show'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:241: in function `CompactRaidFrameContainer_AddGroup'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:215: in function `CompactRaidFrameContainer_AddGroups'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:174: in function `CompactRaidFrameContainer_LayoutFrames'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:130: in function `CompactRaidFrameContainer_TryUpdate'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:57: in function `CompactRaidFrameContainer_OnEvent'\n[string \"*:OnEvent\"]:1: in function <[string \"*:OnEvent\"]:1>\n",
		}, -- [6]
		{
			["message"] = "Note: AddOn BigFoot attempted to call a protected function (CompactPartyFrame:ClearAllPoints()) during combat lockdown.",
			["count"] = 4,
			["addons"] = "  Swatter, v8.2.6377 (SwimmingSeadragon)\n  AtlasLootClassic, vv1.1.8-beta\n  AttackTimer, v\n  AucAdvanced, v8.2.6385 (SwimmingSeadragon)\n  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)\n  AucScanData, v8.2.6365 (SwimmingSeadragon)\n  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)\n  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)\n  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)\n  AucStatSimple, v8.2.6368 (SwimmingSeadragon)\n  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)\n  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)\n  AutoEquip, v\n  BagnonForever, v1.1.1\n  Bartender4, v4.8.5\n  BeanCounter, v8.2.6381 (SwimmingSeadragon)\n  BFGadgets, v\n  BFQuest, v\n  BFTooltip, v\n  BigFoot, v\n  BigFootChat, v\n  BlizzMove, vv1.2.2\n  BuffMaster, v\n  ChannelFilter, v\n  ClassicCodex, v1.2.1\n  ClassicThreatMeter, v1.06\n  Combuctor, v603\n  DBMCore, v1.13.5\n  DBMDefaultSkin, v\n  DBMStatusBarTimers, v\n  Enchantrix, v8.2.6392 (SwimmingSeadragon)\n  EventAlertMod, v8.0.1\n  HandyNotes, vr317\n  HandyNotesDungeonLocationsClassic, v1.01\n  HandyNotesFlightMastersClassic, v1.04\n  HandyNotesTravelGuideClassic, vv2.1.0\n  Informant, v8.2.6374 (SwimmingSeadragon)\n  ItemInfo, v\n  MailMod, v\n  Mapster, v1.8.4\n  Masque, vClassic-8.2.5-Beta-2\n  MerInspect, v2.2.0\n  MonkeyBuddy, v\n  MonkeyLibrary, v\n  MonkeyQuest, v\n  MonkeyQuestLog, v\n  MySlot, vclassic-5.2.6-alpha\n  NeatPlates, v1.13.2.12-Classic\n  NeatPlatesAlvara, v5a\n  NeatPlatesBlizzardPlates, v1.5\n  NeatPlatesClassicPlates, v\n  NeatPlatesGraphite, v\n  NeatPlatesGrey, v\n  NeatPlatesNeon, v\n  NeatPlatesQuatre, v\n  NeatPlatesRenaitre, vv7.0.3\n  NeatPlatesRoth, v\n  NeatPlatesSimple, v7.3.0\n  NeatPlatesSlimHorizontal, v2.2\n  NeatPlatesSlimVertical, v2.2\n  NeatPlatesHub, v\n  NeatPlatesWidgets, v\n  PlayerLink, v\n  QuestFrameFixer, v1.1.1\n  QuestLogEx, v1.2\n  QuickCompare, v\n  RaidAlerter, v5.3.1\n  RealMobHealth, v2.3\n  Recount, vv1.13.2b\n  RepairHelper, v\n  Scrap, v13.19\n  ScrapOptions, v13.19\n  ScrapSpotlight, v13.19\n  SellerHelper, v\n  ShadowedUnitFrames, vv4.2-Classic-Beta6\n  SlideBar, v8.2.6375 (SwimmingSeadragon)\n  Stubby, v8.2.6376 (SwimmingSeadragon)\n  TheBurningTrade, v\n  TrackResources, v0.7\n  TradeSkillMaster, vv4.8.6\n  WhatsTraining, v1.7\n  WhisperPop, v3.1\n  BlizRuntimeLib_zhCN v1.13.2.11302 <none>\n  (ck=8ca)\n",
			["timestamp"] = "2019-09-07 11:20:38",
			["context"] = "AddOn: BigFoot",
			["stack"] = "[C]: in function `ClearAllPoints'\nInterface\\FrameXML\\FlowContainer.lua:157: in function `FlowContainer_DoLayout'\nInterface\\FrameXML\\FlowContainer.lua:17: in function `FlowContainer_ResumeUpdates'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:185: in function `CompactRaidFrameContainer_LayoutFrames'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:130: in function `CompactRaidFrameContainer_TryUpdate'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:57: in function `CompactRaidFrameContainer_OnEvent'\n[string \"*:OnEvent\"]:1: in function <[string \"*:OnEvent\"]:1>\n",
		}, -- [7]
		{
			["message"] = "Note: AddOn BigFoot attempted to call a protected function (CompactPartyFrame:SetPoint()) during combat lockdown.",
			["count"] = 4,
			["addons"] = "  Swatter, v8.2.6377 (SwimmingSeadragon)\n  AtlasLootClassic, vv1.1.8-beta\n  AttackTimer, v\n  AucAdvanced, v8.2.6385 (SwimmingSeadragon)\n  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)\n  AucScanData, v8.2.6365 (SwimmingSeadragon)\n  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)\n  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)\n  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)\n  AucStatSimple, v8.2.6368 (SwimmingSeadragon)\n  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)\n  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)\n  AutoEquip, v\n  BagnonForever, v1.1.1\n  Bartender4, v4.8.5\n  BeanCounter, v8.2.6381 (SwimmingSeadragon)\n  BFGadgets, v\n  BFQuest, v\n  BFTooltip, v\n  BigFoot, v\n  BigFootChat, v\n  BlizzMove, vv1.2.2\n  BuffMaster, v\n  ChannelFilter, v\n  ClassicCodex, v1.2.1\n  ClassicThreatMeter, v1.06\n  Combuctor, v603\n  DBMCore, v1.13.5\n  DBMDefaultSkin, v\n  DBMStatusBarTimers, v\n  Enchantrix, v8.2.6392 (SwimmingSeadragon)\n  EventAlertMod, v8.0.1\n  HandyNotes, vr317\n  HandyNotesDungeonLocationsClassic, v1.01\n  HandyNotesFlightMastersClassic, v1.04\n  HandyNotesTravelGuideClassic, vv2.1.0\n  Informant, v8.2.6374 (SwimmingSeadragon)\n  ItemInfo, v\n  MailMod, v\n  Mapster, v1.8.4\n  Masque, vClassic-8.2.5-Beta-2\n  MerInspect, v2.2.0\n  MonkeyBuddy, v\n  MonkeyLibrary, v\n  MonkeyQuest, v\n  MonkeyQuestLog, v\n  MySlot, vclassic-5.2.6-alpha\n  NeatPlates, v1.13.2.12-Classic\n  NeatPlatesAlvara, v5a\n  NeatPlatesBlizzardPlates, v1.5\n  NeatPlatesClassicPlates, v\n  NeatPlatesGraphite, v\n  NeatPlatesGrey, v\n  NeatPlatesNeon, v\n  NeatPlatesQuatre, v\n  NeatPlatesRenaitre, vv7.0.3\n  NeatPlatesRoth, v\n  NeatPlatesSimple, v7.3.0\n  NeatPlatesSlimHorizontal, v2.2\n  NeatPlatesSlimVertical, v2.2\n  NeatPlatesHub, v\n  NeatPlatesWidgets, v\n  PlayerLink, v\n  QuestFrameFixer, v1.1.1\n  QuestLogEx, v1.2\n  QuickCompare, v\n  RaidAlerter, v5.3.1\n  RealMobHealth, v2.3\n  Recount, vv1.13.2b\n  RepairHelper, v\n  Scrap, v13.19\n  ScrapOptions, v13.19\n  ScrapSpotlight, v13.19\n  SellerHelper, v\n  ShadowedUnitFrames, vv4.2-Classic-Beta6\n  SlideBar, v8.2.6375 (SwimmingSeadragon)\n  Stubby, v8.2.6376 (SwimmingSeadragon)\n  TheBurningTrade, v\n  TrackResources, v0.7\n  TradeSkillMaster, vv4.8.6\n  WhatsTraining, v1.7\n  WhisperPop, v3.1\n  BlizRuntimeLib_zhCN v1.13.2.11302 <none>\n  (ck=8ca)\n",
			["timestamp"] = "2019-09-07 11:20:38",
			["context"] = "AddOn: BigFoot",
			["stack"] = "[C]: in function `SetPoint'\nInterface\\FrameXML\\FlowContainer.lua:161: in function `FlowContainer_DoLayout'\nInterface\\FrameXML\\FlowContainer.lua:17: in function `FlowContainer_ResumeUpdates'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:185: in function `CompactRaidFrameContainer_LayoutFrames'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:130: in function `CompactRaidFrameContainer_TryUpdate'\n...actRaidFrames\\Blizzard_CompactRaidFrameContainer.lua:57: in function `CompactRaidFrameContainer_OnEvent'\n[string \"*:OnEvent\"]:1: in function <[string \"*:OnEvent\"]:1>\n",
		}, -- [8]
		{
			["message"] = "Note: AddOn RealMobHealth attempted to call a protected function (PartyMemberFrame1PetFrame:Hide()) during combat lockdown.",
			["count"] = 1,
			["addons"] = "  Swatter, v8.2.6377 (SwimmingSeadragon)\n  AtlasLootClassic, vv1.1.8-beta\n  AtlasLootClassicDungeonsAndRaids, vv1.1.8-beta\n  AttackTimer, v\n  AucAdvanced, v8.2.6385 (SwimmingSeadragon)\n  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)\n  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)\n  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)\n  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)\n  AucStatSimple, v8.2.6368 (SwimmingSeadragon)\n  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)\n  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)\n  AutoEquip, v\n  BagnonForever, v1.1.1\n  Bartender4, v4.8.5\n  BeanCounter, v8.2.6381 (SwimmingSeadragon)\n  BFGadgets, v\n  BFQuest, v\n  BFTooltip, v\n  BigFoot, v\n  BigFootChat, v\n  BlizzMove, vv1.2.2\n  BuffMaster, v\n  ChannelFilter, v\n  ClassicCodex, v1.2.1\n  ClassicThreatMeter, v1.06\n  Combuctor, v603\n  DBMCore, v1.13.5\n  DBMDefaultSkin, v\n  DBMStatusBarTimers, v\n  Enchantrix, v8.2.6392 (SwimmingSeadragon)\n  EventAlertMod, v8.0.1\n  HandyNotes, vr317\n  HandyNotesDungeonLocationsClassic, v1.01\n  HandyNotesFlightMastersClassic, v1.04\n  HandyNotesTravelGuideClassic, vv2.1.0\n  Informant, v8.2.6374 (SwimmingSeadragon)\n  ItemInfo, v\n  MailMod, v\n  Mapster, v1.8.4\n  Masque, vClassic-8.2.5-Beta-2\n  MerInspect, v2.2.0\n  MonkeyBuddy, v\n  MonkeyLibrary, v\n  MonkeyQuest, v\n  MonkeyQuestLog, v\n  MySlot, vclassic-5.2.6-alpha\n  NeatPlates, v1.13.2.12-Classic\n  NeatPlatesAlvara, v5a\n  NeatPlatesBlizzardPlates, v1.5\n  NeatPlatesClassicPlates, v\n  NeatPlatesGraphite, v\n  NeatPlatesGrey, v\n  NeatPlatesNeon, v\n  NeatPlatesQuatre, v\n  NeatPlatesRenaitre, vv7.0.3\n  NeatPlatesRoth, v\n  NeatPlatesSimple, v7.3.0\n  NeatPlatesSlimHorizontal, v2.2\n  NeatPlatesSlimVertical, v2.2\n  NeatPlatesHub, v\n  NeatPlatesWidgets, v\n  PlayerLink, v\n  QuestFrameFixer, v1.1.1\n  QuestLogEx, v1.2\n  QuickCompare, v\n  RaidAlerter, v5.3.1\n  RealMobHealth, v2.3\n  Recount, vv1.13.2b\n  RepairHelper, v\n  Scrap, v13.19\n  ScrapMerchant, v13.19\n  ScrapSpotlight, v13.19\n  SellerHelper, v\n  ShadowedUnitFrames, vv4.2-Classic-Beta6\n  SlideBar, v8.2.6375 (SwimmingSeadragon)\n  Stubby, v8.2.6376 (SwimmingSeadragon)\n  TheBurningTrade, v\n  TrackResources, v0.7\n  TradeSkillMaster, vv4.8.6\n  WhatsTraining, v1.7\n  WhisperPop, v3.1\n  BlizRuntimeLib_zhCN v1.13.2.11302 <none>\n  (ck=8cf)\n",
			["timestamp"] = "2019-09-07 17:32:36",
			["context"] = "AddOn: RealMobHealth",
			["stack"] = "[C]: in function `Hide'\nInterface\\FrameXML\\PartyMemberFrame.lua:599: in function `PartyMemberFrame_UpdateOnlineStatus'\nInterface\\FrameXML\\PartyMemberFrame.lua:392: in function `PartyMemberFrame_OnEvent'\n[string \"*:OnEvent\"]:1: in function <[string \"*:OnEvent\"]:1>\n",
		}, -- [9]
		{
			["message"] = "Error: AddOn ClassicCodex attempted to call a forbidden function (GuildControlSetRank()) from a tainted execution path.",
			["count"] = 1,
			["addons"] = "  Swatter, v8.2.6377 (SwimmingSeadragon)\n  AtlasLootClassic, vv1.1.8-beta\n  AucAdvanced, v8.2.6385 (SwimmingSeadragon)\n  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)\n  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)\n  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)\n  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)\n  AucStatSimple, v8.2.6368 (SwimmingSeadragon)\n  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)\n  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)\n  Bartender4, v4.8.5\n  BeanCounter, v8.2.6381 (SwimmingSeadragon)\n  ClassicCodex, v1.2.1\n  ClassicThreatMeter, v1.06\n  Enchantrix, v8.2.6392 (SwimmingSeadragon)\n  HandyNotes, vr317\n  HandyNotesDungeonLocationsClassic, v1.01\n  HandyNotesFlightMastersClassic, v1.04\n  HandyNotesTravelGuideClassic, vv2.1.0\n  Informant, v8.2.6374 (SwimmingSeadragon)\n  Masque, vClassic-8.2.5-Beta-2\n  MonkeyBuddy, v\n  MonkeyLibrary, v\n  MonkeyQuest, v\n  MonkeyQuestLog, v\n  NeatPlates, v1.13.2.12-Classic\n  NeatPlatesAlvara, v5a\n  NeatPlatesBlizzardPlates, v1.5\n  NeatPlatesClassicPlates, v\n  NeatPlatesGraphite, v\n  NeatPlatesGrey, v\n  NeatPlatesNeon, v\n  NeatPlatesQuatre, v\n  NeatPlatesRenaitre, vv7.0.3\n  NeatPlatesRoth, v\n  NeatPlatesSimple, v7.3.0\n  NeatPlatesSlimHorizontal, v2.2\n  NeatPlatesSlimVertical, v2.2\n  NeatPlatesHub, v\n  NeatPlatesWidgets, v\n  QuestFrameFixer, v1.1.1\n  QuestLogEx, v1.2\n  RealMobHealth, v2.3\n  Scrap, v13.19\n  ScrapMerchant, v13.19\n  ScrapSpotlight, v13.19\n  ShadowedUnitFrames, vv4.2-Classic-Beta6\n  SlideBar, v8.2.6375 (SwimmingSeadragon)\n  Stubby, v8.2.6376 (SwimmingSeadragon)\n  TrackResources, v0.7\n  TradeSkillMaster, vv4.8.6\n  WhatsTraining, v1.7\n  BlizRuntimeLib_zhCN v1.13.2.11302 <none>\n  (ck=682)\n",
			["timestamp"] = "2019-09-08 15:04:32",
			["context"] = "AddOn: ClassicCodex",
			["stack"] = "[C]: in function `GuildControlSetRank'\nInterface\\FrameXML\\FriendsFrame.lua:2514: in function `func'\nInterface\\FrameXML\\UIDropDownMenu.lua:958: in function `UIDropDownMenuButton_OnClick'\n[string \"*:OnClick\"]:1: in function <[string \"*:OnClick\"]:1>\n",
		}, -- [10]
	},
	["autoshow"] = true,
}
